import type { Perspective } from "@/lib/types";

/**
 * Perspectives — the firm's point of view (target: one per quarter), plus
 * the historical press reposts archived as "Transactions" (§4.6).
 *
 * FALLBACK ONLY. The live content is the engagement hub's `perspectives`
 * table, edited in its Perspectives module (lib/data.ts → getPerspectives);
 * this snapshot serves when the hub is unreachable or not configured. It
 * was seeded into the hub by its migration
 * 20260915000001_website_perspectives.sql — edit there, not here.
 *
 * The transaction archive (§9) is imported in full from the WordPress
 * export, back to 2010. Each transaction is a compact timeline row: title,
 * date, one line, link out.
 */
export const perspectives: Perspective[] = [
  {
    id: "1",
    slug: "ai-as-core-capability",
    title: "AI as a core capability",
    author_slug: "jason-salgo",
    kind: "perspective",
    published_at: "2026-02-15",
    excerpt:
      "Over the past year, AI moved from experiment to daily production across our engagements. What that actually took, and why most pilots never get there.",
    body_md: `Over the past year, AI at Fairlead moved from experiment to daily production. Not a pilot, not a proof of concept: tools our teams use every day, inside live engagements, for more than six months now.

That distinction matters because most firms are stuck at the pilot phase. The industry data is blunt: the overwhelming majority of corporate AI pilots never reach production. The gap isn't the models. It's the implementation threshold: the unglamorous work of wiring a tool into how a company actually closes its books, pays its vendors, and reports to its board.

We crossed that threshold the only way we know: from inside the companies. Every tool we run started as a specific answer to a specific client's pain: a 13-week cash forecast a sponsor could trust before every meeting, a board pack that assembles itself from live data with a full audit trail, an assistant that noticed our client's largest customer was being undercharged.

Because the tools were built against real operating problems, they generalize. And because we've been embedded in PE-backed companies since 2010, the data they learn from is the kind you can't buy: fifteen years of operating history, captured from the seat.

We are not the most vocal participants in discussions about AI. But when a portfolio company asks whether an approach will work, we answer from experience rather than optimism.

*TODO: replace with the edited full text of Jason's February 2026 post.*`,
    external_url: null,
    visible: true,
  },
  // ---- Transactions (historical reposts — compact timeline) ----
  {
    id: "t1",
    slug: "dion-leadership-gallagher",
    title: "Fairlead supports Dion Leadership in its sale to Gallagher",
    author_slug: null,
    kind: "transaction",
    published_at: "2025-12-01",
    excerpt: "Sale process support from preparation to close.",
    body_md: null,
    external_url: null, // TODO: link to original release
    visible: true,
  },
  {
    id: "t2",
    slug: "nirenberg-neuroscience-sale",
    title: "Fairlead advises Nirenberg Neuroscience through its sale",
    author_slug: null,
    kind: "transaction",
    published_at: "2023-05-01",
    excerpt: "M&A advisory through diligence and close.",
    body_md: null,
    external_url: null, // TODO: link to original release
    visible: true,
  },
  {
    id: "t3",
    slug: "survival-sprint-case-study",
    title: "Case study: the survival sprint",
    author_slug: null,
    kind: "transaction",
    published_at: "2023-06-01",
    excerpt: "Cash control, overhead discipline, and the path to financing.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t4",
    slug: "product-insight-sale",
    title: "Fairlead Advisors facilitates successful sale of Product Insight",
    author_slug: null,
    kind: "transaction",
    published_at: "2024-08-27",
    excerpt: "Strategic advisory on the sale of the operational-efficiency consultancy to an internal buyer.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t5",
    slug: "singrobo-hydropower-power-deal-of-the-year",
    title: "Singrobo hydropower plant wins Power Deal of the Year award",
    author_slug: null,
    kind: "transaction",
    published_at: "2024-04-03",
    excerpt: "The 44 MW Singrobo plant, first hydropower IPP to reach financial close in West Africa, wins at the IJGlobal Awards.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t6",
    slug: "xpdb-montana-technologies-business-combination",
    title: "Power & Digital Infrastructure Acquisition II Corp. (XPDB) closes business combination with Montana Technologies",
    author_slug: null,
    kind: "transaction",
    published_at: "2024-03-14",
    excerpt: "Business combination closing brings Montana Technologies to Nasdaq under the AIRJ ticker.",
    body_md: null,
    external_url:
      "https://www.prnewswire.com/news-releases/power--digital-infrastructure-acquisition-ii-corp-xpdb-announces-closing-of-business-combination-with-montana-technologies-llc-302089782.html",
    visible: true,
  },
  {
    id: "t7",
    slug: "klx-acquires-greenes-energy-group",
    title: "KLX Energy Services completes acquisition of Greene's Energy Group",
    author_slug: null,
    kind: "transaction",
    published_at: "2023-03-08",
    excerpt: "All-stock, deleveraging transaction adding scope and scale to KLX's Southwest segment.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t8",
    slug: "grp-holdco-tax-credit-monetization",
    title: "GRP Holdco monetizes $82.5 million of production tax credits",
    author_slug: null,
    kind: "transaction",
    published_at: "2023-03-07",
    excerpt: "$82.5 million tax equity financing across 116 MW of biomass projects in Georgia.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t9",
    slug: "lighthouse-guild-bionic-sight-partnership",
    title: "Lighthouse Guild and Bionic Sight announce partnership",
    author_slug: null,
    kind: "transaction",
    published_at: "2022-11-29",
    excerpt: "Partnership expanding treatment options for people with advanced-stage blindness.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t10",
    slug: "vauban-district-energy-acquisition",
    title: "Vauban Infrastructure Partners acquires district energy platform",
    author_slug: null,
    kind: "transaction",
    published_at: "2021-12-30",
    excerpt: "Agreement to acquire a portfolio of eight district cooling and heating systems, including Detroit Thermal.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t11",
    slug: "ambri-liquid-metal-battery-financing",
    title: "Ambri secures $144 million for liquid metal battery commercialization",
    author_slug: null,
    kind: "transaction",
    published_at: "2021-08-10",
    excerpt: "MIT-spinoff long-duration battery developer raises to build U.S. and international manufacturing.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t12",
    slug: "greenleaf-power-project-financing",
    title: "Fairlead advises Greenleaf Power on $36.7M renewable project financing",
    author_slug: null,
    kind: "transaction",
    published_at: "2021-06-14",
    excerpt: "One of the largest biomass power project financings in recent North American history.",
    body_md: null,
    external_url:
      "https://www.privateequitywire.co.uk/2021/06/08/301555/greenleaf-power-secures-usd367m-financing-east-west-bank",
    visible: true,
  },
  {
    id: "t13",
    slug: "bentley-systems-acquires-sensemetrics",
    title: "Bentley Systems acquires sensemetrics",
    author_slug: null,
    kind: "transaction",
    published_at: "2021-04-29",
    excerpt: "Acquisition adds IoT capabilities for infrastructure digital twins to the Bentley iTwin platform.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t14",
    slug: "bionic-sight-collaboration-agreement",
    title: "Bionic Sight enters into collaboration agreement",
    author_slug: null,
    kind: "transaction",
    published_at: "2020-08-18",
    excerpt: "Fairlead supported the negotiation of Bionic Sight's strategic collaboration with Applied Genetic Technologies.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t15",
    slug: "veolia-sells-district-energy-assets",
    title: "Veolia sells U.S. district energy assets to Antin Infrastructure Partners",
    author_slug: null,
    kind: "transaction",
    published_at: "2019-08-19",
    excerpt: "$1.25 billion sale of steam, hot and chilled water, and cogeneration assets across 10 markets.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t16",
    slug: "luminoso-series-b-financing",
    title: "Luminoso secures $10 million in Series B financing",
    author_slug: null,
    kind: "transaction",
    published_at: "2018-12-06",
    excerpt: "Round led by DVI Equity Partners for the AI-powered customer insights company.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t17",
    slug: "novus-energy-biomass-plant-sale",
    title: "Novus Energy sells biomass plant to WRZ Hörger",
    author_slug: null,
    kind: "transaction",
    published_at: "2016-12-06",
    excerpt: "Sale of a German CHP biomass plant completes Novus Energy's exit from the bio energy market.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t18",
    slug: "ford-autonomous-vehicle-investments",
    title: "Ford targets fully autonomous vehicle for ride sharing in 2021",
    author_slug: null,
    kind: "transaction",
    published_at: "2016-08-16",
    excerpt: "Investments in new tech companies and a doubled Silicon Valley team back Ford's autonomous push.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t19",
    slug: "kacare-clean-energy-strategy",
    title: "K.A.CARE speeds up work on 'clean energy' strategy",
    author_slug: null,
    kind: "transaction",
    published_at: "2015-07-08",
    excerpt: "K.A.CARE accelerates the blueprint for Saudi Arabia's renewable energy strategy.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t20",
    slug: "us-silica-acquires-cadre-services",
    title: "U.S. Silica acquires Cadre Services for $98 million",
    author_slug: null,
    kind: "transaction",
    published_at: "2014-07-16",
    excerpt: "Acquisition of the regional frac sand producer expands U.S. Silica's Permian Basin footprint.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t21",
    slug: "vitag-financing-tpg",
    title: "TPG leads equity portion of $110M financing for VitAg",
    author_slug: null,
    kind: "transaction",
    published_at: "2014-07-14",
    excerpt: "Equity and debt financing for the specialty fertilizer producer, led by TPG Capital.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t22",
    slug: "kemet-acquires-niotan",
    title: "KEMET completes acquisition of Niotan",
    author_slug: null,
    kind: "transaction",
    published_at: "2012-02-21",
    excerpt: "Acquisition of the tantalum powder manufacturer from an affiliate of Denham Capital Management.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  {
    id: "t23",
    slug: "constellation-energy-acquires-mxenergy",
    title: "Constellation Energy purchases MXenergy",
    author_slug: null,
    kind: "transaction",
    published_at: "2011-05-12",
    excerpt: "All-cash acquisition of the retail natural gas and electricity supplier by Constellation Energy.",
    body_md: null,
    external_url: "https://www.prnewswire.com/news-releases/constellation-energy-purchases-mxenergy-121725878.html",
    visible: true,
  },
  {
    id: "t24",
    slug: "detroit-thermal-energy-system-financing",
    title: "Detroit Thermal attracts $50 million for energy system",
    author_slug: null,
    kind: "transaction",
    published_at: "2010-11-16",
    excerpt: "Investment secures a long-term, cost-effective supply of renewable energy for Detroit's core business district.",
    body_md: null,
    external_url: null,
    visible: true,
  },
  // Team Member Spotlight - Carolina Andrés (2023-07-24) and Mary Day's
  // Reflections on Working at Fairlead (2023-10-11) are on the legacy site's
  // announcements feed but are team/culture posts, not deal or firm-view
  // content, so they don't fit either Perspective kind — left out.
];
